### ISSUE TITLE
Error while upgrading to 4.7.3

### ISSUE THREAD

**Issue by anshulkhattar** [argyle-systems/argyle-plugin-android#13]
Hello all,

Facing sync/build issues while upgrading to Argyle Link 4.7.3

Sync - 
`Failed to resolve: com.argyle:argyle-plugin-android-source:4.7.3`

Build - 
`* What went wrong:
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.argyle:argyle-plugin-android-source:4.7.3.
`

Please help resolving this.

**Comment by Varnius** [comment]
@anshulkhattar Hi! 
Starting with `4.7.3` we migrated the package to Maven Central and the package name changed from `com.argyle:argyle-plugin-android-source` to `com.argyle:argyle-link-android` - once you change that it should be able to resolve it.

**Comment by anshulkhattar** [comment]
> @anshulkhattar Hi!
> Starting with `4.7.3` we migrated the package to Maven Central and the package name changed from `com.argyle:argyle-plugin-android-source` to `com.argyle:argyle-link-android` - once you change that it should be able to resolve it.

Thanks @Varnius , it's working now.
