### ISSUE TITLE
check view != null before access it

### ISSUE THREAD

**Issue by Polurival** [argyle-systems/argyle-plugin-android#16]
com.argyle:argyle-link-android:5.4.0

java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner for IntroFragment{51376f3} (52ad755b-b7b0-4758-bff4-6222926d43f2) when getView() is null i.e., before onCreateView() or after onDestroyView()
    androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:385)
    com.argyle.ui.utils.FragmentViewBindingDelegate.a(SourceFile:6)
    com.argyle.ui.features.intro.IntroFragment.d(SourceFile:1)
    com.argyle.ui.features.intro.a.onAnimationEnd(SourceFile:2)
    android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
    android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:711)
    android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(:4)
    android.animation.Animator.callOnList(Animator.java:669)
    android.animation.Animator.notifyListeners(Animator.java:608)
    android.animation.Animator.notifyEndListeners(Animator.java:633)
    android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
    android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1566)
    android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
    android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(:0)
    android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
    android.view.Choreographer.doCallbacks(Choreographer.java:952)
    android.view.Choreographer.doFrame(Choreographer.java:878)
    android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
    android.os.Handler.handleCallback(Handler.java:958)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loopOnce(Looper.java:205)
    android.os.Looper.loop(Looper.java:294)
    android.app.ActivityThread.main(ActivityThread.java:8177)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by MindaugasVarkalys** [comment]
@Polurival thank you for opening an issue. However, we are unable to reproduce this exception. Can you provide more details on how it occurred? Android version, your `LinkConfig`, and screen recording would help us a lot to identify the problem.

**Comment by Polurival** [comment]
this bug from Crashlytics, sorry, i can't give what you ask.

Looks like in IntroFragment where is some ViewPropertyAnimator
which lifecycle is more then between onCreateView-onDestroyView

Please cancel animation in onDestroyView, it probably will help.
One of case:
https://stackoverflow.com/a/44112869

**Comment by Polurival** [comment]
@MindaugasVarkalys

**Comment by MindaugasVarkalys** [comment]
@Polurival I potentially fixed the issue although I couldn't reproduce it. You can test the fix in version `5.5.1`. If you still see the crashes, let us know.
