### ISSUE TITLE
make safe cast as? or add check on null before cast

### ISSUE THREAD

**Issue by Polurival** [argyle-systems/argyle-plugin-android#17]
com.argyle:argyle-link-android:5.4.0

java.lang.NullPointerException: null cannot be cast to non-null type com.argyle.ui.features.search.SuggestionsGridLayoutManager
    com.argyle.ui.features.search.n.invokeSuspend(SourceFile:6)
    kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    kotlinx.coroutines.internal.DispatchedContinuation.resumeUndispatchedWith(DispatchedContinuation.java:254)
    kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:176)
    kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:189)
    kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
    kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
    kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
    kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
    kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
    com.argyle.ui.utils.c$b.onAnimationEnd(SourceFile:5)
    android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
    android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
    android.animation.AnimatorSet.end(AnimatorSet.java:515)
    android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:436)
    android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1002)
    android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
    android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(:0)
    android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
    android.view.Choreographer.doCallbacks(Choreographer.java:923)
    android.view.Choreographer.doFrame(Choreographer.java:847)
    android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
    android.os.Handler.handleCallback(Handler.java:942)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loopOnce(Looper.java:226)
    android.os.Looper.loop(Looper.java:313)
    android.app.ActivityThread.main(ActivityThread.java:8762)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by MindaugasVarkalys** [comment]
@Polurival thank you for opening an issue. However, we are unable to reproduce this exception. Can you provide more details on how it occurred? Android version, your `LinkConfig`, and screen recording would help us a lot to identify the problem.

**Comment by Polurival** [comment]
this bug from Crashlytics, sorry, i can't give what you ask.

Looks like in SuggestionsGridLayoutManager or near this class
where is some AnimatorSet animation
which lifecycle is more then between onCreateView-onDestroyView

Please cancel animation in onDestroyView, it probably will help.

**Comment by Polurival** [comment]
@MindaugasVarkalys

**Comment by MindaugasVarkalys** [comment]
@Polurival I potentially fixed the issue although I couldn't reproduce it. You can test the fix in version `5.5.1`. If you still see the crashes, let us know.
