### ISSUE TITLE
Error on Build - Unauthorized from jitpack

### ISSUE THREAD

**Issue by chgsilva** [argyle-systems/argyle-plugin-android#2]
Hello all, 

I started to receive this error on Android Build today, yesterday was working:
```
      > Could not resolve com.argyle:argyle-plugin-android-source:3.2.0.
         > Could not get resource 'https://jitpack.io/com/argyle/argyle-plugin-android-source/3.2.0/argyle-plugin-android-source-3.2.0.pom'.
            > Could not GET 'https://jitpack.io/com/argyle/argyle-plugin-android-source/3.2.0/argyle-plugin-android-source-3.2.0.pom'. Received status code 401 from server: Unauthorized
```

I double check on the documentation and there is nothing about auth on jitpack. Has something changed? Any hints on how to solve it?

**Comment by Varnius** [comment]
@chgsilva Thanks for reporting - we will investigate.

**Comment by Varnius** [comment]
@chgsilva Seems there were some temporary issues on Jitpack side that were already resolved. Does it work for you now?

**Comment by chgsilva** [comment]
Thanks @Varnius , it is working right now
